project:
  type: website
  output-dir: docs

# Meta
description-meta: "Personal website of Daria Ardelean"
author-meta: "Daria Ardelean"

website:
  title: "Daria Ardelean"
  description: "Personal website of Daria Ardelean"

  navbar:
    background: light
    left:
      - text: About
        href: index.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

    right:
      - icon: github
        href: https://github.com/dariaalexiaardelean
        target: _blank

  page-navigation: true

  page-footer:
    left: "Daria Ardelean &copy; <script>document.write(new Date().getFullYear())</script>"
  
    

  reader-mode: false
  
  draft-mode: unlinked

  repo-url: https://github.com/dariaalexiaardelean/daria_ardelean

  open-graph: true
  twitter-card: true

  site-url: "https://dariaalexiaardelean.github.io/daria_ardelean"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    include-in-header: "files/includes/_academic.qmd"
